# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_send', models.EmailField(max_length=254)),
                ('name_send', models.CharField(max_length=128)),
                ('email_addres', models.EmailField(max_length=254)),
                ('name_addres', models.CharField(max_length=128)),
                ('bet_name', models.CharField(max_length=128)),
                ('bet_body', models.TextField(blank=True, default=None, null=True)),
                ('bet_end', models.DateField()),
                ('bet_status', models.BooleanField(default=False)),
                ('active_code', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Спорин',
                'verbose_name': 'Спорин',
            },
        ),
    ]
